config/routes.rb
MyFirstRails::Application.routes.draw do
  
  root to: 'static_pages#home'
  match '/contact', to: 'static_pages#contact'
  match '/about', to: 'static_pages#about'
  match '/kitchens', to: 'static_pages#kitchens'
  match '/projects', to: 'static_pages#projects'
  match '/baths', to: 'static_pages#baths'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def kitchens
  end

  def projects
  end

  def baths
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

# Below returns the full base title plus the specific pages title.  If it has one.
  def full_title(page_title)
    base_title = "Studio One Designs LLC - Kitchens, Baths, & Additions"
    if page_title.empty?
      base_title
    else
      "#{base_title} - #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &nbsp;developed by Matthew Schultz
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <table border ="0">
	<tr>
	  <td rowspan="1">
	    <%= image_tag("studioOneTrimmed.jpg", alt: "No image available") %>
	  </td>
	  <td align = "right">
	    <p>Squirrel Hill Showroom: 412-422-8200</p>
	    <nav>
	      <ul class="nav pull-right">
		<li><%= link_to "Home",    root_path %></li>
		<li><%= link_to "About Us", about_path %></li>
		<li><%= link_to "Products", '#' %></li>
		<li><%= link_to "Contact Us", contact_path %></li>
	      </ul>
	    </nav>
	  </td>
	</tr>
	<!--<tr>
	  <td rowspan = "2">
	    <p1>A boutique design firm creating custom kitchens contoured to your needs.<br/>
	      Over 100 years of combined experience in contracting and design.</p1>
	  </td>  
	  <td>
	     <%= link_to image_tag("facebook_logo.jpg", alt: "No image available"), 'https://www.facebook.com/pages/Frankies/122858467774600/'%>
	  </td>
	</tr>-->
      </table>
    </div>
  </div>
</header>

app/views/layouts/_header.html_UNCHANGED.erb
<!--<header class="navbar navbar-fixed-top navbar-inverse">-->
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <table border = 0>
	<tleft>
	<!--<td><%= link_to image_tag("studioOneTrimmed.jpg", alt: "Rails"), 'http://localhost:3000/static_pages/home/' %></td>-->
	  <tr>
	    <td rowspan="2">
	      <%= image_tag("studioOneTrimmed.jpg", alt: "Rails") %>
	    </td>
	  </tr>
	</tleft>    
	<td>
	      <nav>
		<ul class="nav pull-right">
		  <li><%= link_to "Home",    '#' %></li>
		  <li><%= link_to "About Studio One",'#' %></li>
		  <li><%= link_to "Specialty Products", '#' %></li>
		  <li><%= link_to "Contact", '#' %></li>
		</ul>
	      </nav>
	    </td>
	  </tr>
	<!--</tr>-->
      </table>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="center hero-unit">
    <table border = 0 cellpadding="4px">
      	<tr>
	  <td>	
	    ABOUT US.  What will we add here.
	  </td>
	</tr>  
    </table>

app/views/static_pages/baths.html.erb
<div class="center hero-unit">
    <table border="0" cellpadding="5px" name="kitchen_table">
      <tr>
	<td>
	  <%= image_tag("baths_page/roma_pos_1.jpg", alt: "No image") %>
	</td>
	<td>
	  <%= image_tag("baths_page/general_bath_caption.jpg", alt: "No image") %>
	</td>
      </tr>
      <tr>
	<td>
	  <%= image_tag("baths_page/roma_pos_2.jpg", alt: "No image") %>
	</td>
	<td>
	  <%= image_tag("baths_page/general_bath_caption.jpg", alt: "No image") %>
	</td>
      </tr>
      <tr>
	<td>
	  <%= image_tag("baths_page/sharma_pos_3.jpg", alt: "No image") %>
	</td>
	<td>
	  <%= image_tag("baths_page/general_bath_caption.jpg", alt: "No image") %>
	</td>
      </tr>
      <tr>
	<td>
	  <%= image_tag("baths_page/spiegel_pos_4.jpg", alt: "No image") %>
	</td>
      	<td>
	  <%= image_tag("baths_page/general_bath_caption.jpg", alt: "No image") %>
	</td>
      </tr>
    </table>

app/views/static_pages/contact.html.erb
<div class="center hero-unit">
    <table border = 0 cellpadding="4px">
      	<tr>
	  <td>
	    <%= image_tag("contact_page/generic_building.jpg", alt: "No image") %>
	    </td>
	  <td>
	    contact us.  Need to add info.
	  </td>
	</tr>  
    </table>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
    <table border = 0 cellpadding="4px">
      	<tr>
	  <td rowspan>
	    <p1>A boutique design firm creating custom kitchens contoured to your needs.<br/>
	      Over 100 years of combined experience in contracting and design.</p1>
	  </td>  
	  <td>
	     <%= link_to image_tag("facebook_logo.jpg", alt: "No image available"), 'https://www.facebook.com/pages/Frankies/122858467774600/'%>
	  </td>
	</tr>


      <tr>
	<td rowspan = "2">
	  <%= link_to image_tag("costelloKitchen.jpg", alt: "No image"), kitchens_path %>
	</td>
	<td>
	  <%= link_to image_tag("roseTeaCounter.jpg", alt: "No image"), projects_path %>
	</td>
      </tr>
      <tr>
	<td>
	  <%= link_to image_tag("spiegelBath.jpg", alt: "Rails"), baths_path %>
	</td>
      </tr>
    </table>
    <table rowspan = "2" cellpadding="4px">
      <tr>
	<td>
	  <p3>We may want to add some text here.</p3>
	</td>
      </tr>
    </table>

app/views/static_pages/kitchens.html.erb
<div class="center hero-unit">
    <table border="0" cellpadding="5px" name="kitchen_table">
      <tr>
	<td>
	  <%= image_tag("kitchen_page/costello_pos_1.jpg", alt: "No image") %>
	</td>
	<td>
	  <%= image_tag("kitchen_page/jucha_pos_2.jpg", alt: "No image") %>
	</td>
      </tr>
      <tr>
	<td>
	  <%= image_tag("kitchen_page/general_kitchen_caption.jpg", alt: "No image") %>
	</td>
	<td>
	  <%= image_tag("kitchen_page/general_kitchen_caption.jpg", alt: "No image") %>
	</td>
      </tr>
      <tr>
	<td>
	  <%= image_tag("kitchen_page/yoder_pos_3.jpg", alt: "No image") %>
	</td>
	<td>
	  <%= image_tag("kitchen_page/wassel_pos_4.jpg", alt: "No image") %>
	</td>
      </tr>
      <tr>
	<td>
	  <%= image_tag("kitchen_page/general_kitchen_caption.jpg", alt: "No image") %>
	</td>
      	<td>
	  <%= image_tag("kitchen_page/general_kitchen_caption.jpg", alt: "No image") %>
	</td>
      </tr>
    </table>

app/views/static_pages/projects.html.erb
<div class="center hero-unit">
    <table border="0" cellpadding="5px" name="projects_table">
      <tr>
	<td>
	  <%= image_tag("projects_page/martin_pos_1.jpg", alt: "No image") %>
	</td>
	<td>
	  <%= image_tag("projects_page/caplan_pos_2.jpg", alt: "No image") %>
	</td>
	<td>
	  <%= image_tag("projects_page/caplan_pos_3.jpg", alt: "No image") %>
	</td>
	<td>
	  <%= image_tag("projects_page/rio_pos_4.jpg", alt: "No image") %>
	</td>
      </tr>
      <tr>
	<td>
	  <%= image_tag("projects_page/general_project_caption.jpg", alt: "No image") %>
	</td>
	<td>
	  <%= image_tag("projects_page/general_project_caption.jpg", alt: "No image") %>
	</td>
	<td>
	  <%= image_tag("projects_page/general_project_caption.jpg", alt: "No image") %>
	</td>
      	<td>
	  <%= image_tag("projects_page/general_project_caption.jpg", alt: "No image") %>
	</td>
      </tr>
    </table>